pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio

trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'
  inputs:
    versionSpec: '4.9.1'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '*.sln'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '*.sln'
    platform: 'Any CPU'
    configuration: 'Release'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '*.sln'
    platform: 'Any CPU'
    configuration: 'Debug'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: 'LCU.NET.Extras/*.csproj'
    versioningScheme: off
    includeReferencedProjects: true

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'http://212.81.198.102:8085/'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

